plugins {
    id 'fabric-loom' version '1.10.5'
    id 'maven-publish'
}

version = "${minecraft_version}-${mod_version}"
group = mod_group_id

base {
    archivesName = mod_id
}

repositories {
    maven {
        name = 'Fuzs Mod Resources'
        url = 'https://raw.githubusercontent.com/Fuzss/modresources/main/maven/'
    }
    maven {
        name = 'Ladysnake'
        url = 'https://maven.ladysnake.org/releases'
    }
    maven {
        name = 'TerraformersMC'
        url = 'https://maven.terraformersmc.com/'
    }
    maven {
        name = 'Curse Maven'
        url = 'https://www.cursemaven.com'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()

    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    modImplementation "dev.emi:trinkets:${trinkets_version}"
    modApi "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${forge_config_api_port_version}"
    modImplementation "dev.onyxstudios.cardinal-components-api:cardinal-components-base:${cardinal_components_version}"
    modImplementation "dev.onyxstudios.cardinal-components-api:cardinal-components-entity:${cardinal_components_version}"
    include "dev.onyxstudios.cardinal-components-api:cardinal-components-base:${cardinal_components_version}"
    include "dev.onyxstudios.cardinal-components-api:cardinal-components-entity:${cardinal_components_version}"
    modCompileOnly("curse.maven:serene-seasons-291874:6398228") { transitive = false }
    modCompileOnly("curse.maven:glitchcore-955399:5787838") { transitive = false }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

sourceSets.main.java {
    exclude 'sfiomn/legendarysurvivaloverhaul/data/DataGenerators.java'
    exclude 'sfiomn/legendarysurvivaloverhaul/data/integration/**'
    exclude 'sfiomn/legendarysurvivaloverhaul/data/loot/**'
    exclude 'sfiomn/legendarysurvivaloverhaul/data/providers/**'
    exclude 'sfiomn/legendarysurvivaloverhaul/data/recipes/**'
    exclude '**/api/data/providers/**'
    exclude '**/common/events/CommonForgeEvents.java'
    exclude '**/common/events/CommonModBusEvents.java'
    exclude '**/client/events/ClientForgeEvents.java'
    exclude '**/client/render/RenderTemperatureOverlay.java'
    exclude '**/client/render/RenderTooltipFrame.java'
    exclude '**/client/render/RenderBlurOverlay.java'
    exclude '**/client/shaders/FocusShader.java'
    exclude '**/client/integration/sereneseasons/RenderSeasonCards.java'
    exclude '**/client/tooltips/TooltipHandler.java'
    exclude '**/common/integration/eclipticseasons/**'
    exclude '**/common/integration/origins/**'
    exclude '**/common/integration/jei/**'
    exclude '**/common/integration/crayfish/CrayfishFurnitureUtil.java'
    exclude '**/common/integration/mutantmonsters/**'
    exclude '**/common/integration/supplementaries/SupplementariesUtil.java'
    exclude '**/common/integration/vampirism/**'
    exclude '**/common/integration/terrafirmacraft/TerraFirmaCraftHeatItemModifier.java'
    exclude '**/common/integration/terrafirmacraft/TerraFirmaCraftModifier.java'
    exclude '**/common/listeners/EnchantmentListener.java'
    exclude '**/common/level/gen/ModBiomeModifiers.java'
    exclude '**/registry/LootModifierRegistry.java'
    exclude '**/common/loot_modifiers/**'
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'minecraft_version', minecraft_version

    filesMatching('fabric.mod.json') {
        expand 'version': project.version, 'minecraft_version': minecraft_version
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.release = 17
    options.encoding = 'UTF-8'
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifactId = mod_id
            from components.java
        }
    }
}
